CREATE EXTENSION IF NOT EXISTS PGCRYPTO;

CREATE TABLE IF NOT EXISTS AUTHORIZATION_TOKEN
(
    ID CHARACTER VARYING(255) NOT NULL,
    ACCESS_TOKEN_EXPIRES_AT TIMESTAMP(6) WITH TIME ZONE,
    ACCESS_TOKEN_ISSUED_AT TIMESTAMP(6) WITH TIME ZONE,
    ACCESS_TOKEN_METADATA OID,
    ACCESS_TOKEN_SCOPES CHARACTER VARYING(1000),
    ACCESS_TOKEN_TYPE CHARACTER VARYING(255),
    ACCESS_TOKEN_VALUE OID,
    ATTRIBUTES OID,
    AUTHORIZATION_CODE_EXPIRES_AT TIMESTAMP(6) WITH TIME ZONE,
    AUTHORIZATION_CODE_ISSUED_AT TIMESTAMP(6) WITH TIME ZONE,
    AUTHORIZATION_CODE_METADATA CHARACTER VARYING(255),
    AUTHORIZATION_CODE_VALUE OID,
    AUTHORIZATION_GRANT_TYPE CHARACTER VARYING(255),
    AUTHORIZED_SCOPES CHARACTER VARYING(1000),
    OIDC_ID_TOKEN_CLAIMS OID,
    OIDC_ID_TOKEN_EXPIRES_AT TIMESTAMP(6) WITH TIME ZONE,
    OIDC_ID_TOKEN_ISSUED_AT TIMESTAMP(6) WITH TIME ZONE,
    OIDC_ID_TOKEN_METADATA OID,
    OIDC_ID_TOKEN_VALUE OID,
    PRINCIPAL_NAME CHARACTER VARYING(255),
    REFRESH_TOKEN_EXPIRES_AT TIMESTAMP(6) WITH TIME ZONE,
    REFRESH_TOKEN_ISSUED_AT TIMESTAMP(6) WITH TIME ZONE,
    REFRESH_TOKEN_METADATA OID,
    REFRESH_TOKEN_VALUE OID,
    REGISTERED_CLIENT_ID CHARACTER VARYING(255),
    STATE CHARACTER VARYING(500),
    CONSTRAINT AUTHORIZATION_PKEY PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS CLIENT
(
    ID CHARACTER VARYING(255)  NOT NULL,
    AUTHORIZATION_GRANT_TYPES CHARACTER VARYING(1000) ,
    CLIENT_AUTHENTICATION_METHODS CHARACTER VARYING(1000) ,
    CLIENT_ID CHARACTER VARYING(255) ,
    CLIENT_ID_ISSUED_AT TIMESTAMP(6) WITH TIME ZONE,
    CLIENT_NAME CHARACTER VARYING(255) ,
    CLIENT_SECRET CHARACTER VARYING(255) ,
    CLIENT_SECRET_EXPIRES_AT TIMESTAMP(6) WITH TIME ZONE,
    CLIENT_SETTINGS CHARACTER VARYING(2000) ,
    REDIRECT_URIS CHARACTER VARYING(1000) ,
    SCOPES CHARACTER VARYING(1000) ,
    TOKEN_SETTINGS CHARACTER VARYING(2000) ,
    CONSTRAINT CLIENT_PKEY PRIMARY KEY (ID)
)

CREATE TABLE IF NOT EXISTS ROLE
(
    ID BIGSERIAL NOT NULL,
	NAME CHARACTER VARYING(60) NOT NULL UNIQUE,
    DESCRIPTION CHARACTER VARYING(255),
    USER_TYPE CHARACTER VARYING(30),
    IS_DEFAULT BOOLEAN NOT NULL DEFAULT FALSE,
    ACTIVE BOOLEAN NOT NULL DEFAULT FALSE,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    CREATED_BY BIGINT NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    UPDATED_BY BIGINT NOT NULL,
    CONSTRAINT ROLE_PKEY PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS MODULES
(
    ID BIGSERIAL NOT NULL,
	NAME CHARACTER VARYING(60) UNIQUE,
	NO_PARENT_MODULE BOOLEAN NOT NULL DEFAULT FALSE,
    PARENT_MODULE_NAME CHARACTER VARYING(60) NOT NULL, 
    AVAILABLE_FOR_SUPER_ADMIN BOOLEAN DEFAULT FALSE,
    AVAILABLE_FOR_USER BOOLEAN DEFAULT FALSE,
    AVAILABLE_FOR_VENDOR BOOLEAN DEFAULT FALSE,
    AVAILABLE_FOR_VENDOR_USER BOOLEAN DEFAULT FALSE,
    ACTIVE BOOLEAN NOT NULL DEFAULT FALSE,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    CREATED_BY BIGINT NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    UPDATED_BY BIGINT NOT NULL,
    CONSTRAINT MODULES_PKEY PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS PERMISSION
(
    ID BIGSERIAL NOT NULL,
	ROLE_ID BIGINT NOT NULL,
    MODULES_ID BIGINT NOT NULL,
    CAN_ADD BOOLEAN NOT NULL DEFAULT FALSE,
    CAN_EDIT BOOLEAN NOT NULL DEFAULT FALSE,
    CAN_VIEW BOOLEAN NOT NULL DEFAULT FALSE,
    CAN_DELETE BOOLEAN NOT NULL DEFAULT FALSE,
    CAN_VIEW_SIDEBAR BOOLEAN NOT NULL DEFAULT FALSE,
    ACTIVE BOOLEAN NOT NULL DEFAULT FALSE,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    CREATED_BY BIGINT NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    UPDATED_BY BIGINT NOT NULL,
    CONSTRAINT PERMISSION_PKEY PRIMARY KEY (ID),
    CONSTRAINT PERMISSION_MODULES FOREIGN KEY (MODULES_ID)
        REFERENCES MODULES (ID),
    CONSTRAINT PERMISSION_ROLE FOREIGN KEY (ROLE_ID)
        REFERENCES ROLE (ID),
    CONSTRAINT MODULE_ROLE UNIQUE (MODULES_ID, ROLE_ID)
);

CREATE TABLE IF NOT EXISTS USER_LOGIN(
	ID BIGSERIAL NOT NULL,
	ENTITY_ID BIGINT ,
	ENTITY_TYPE CHARACTER VARYING(30),
	EMAIL CHARACTER VARYING(255),
	CONTACT_NUMBER CHARACTER VARYING(15),
	OTP CHARACTER VARYING(255),
	PASSWORD CHARACTER VARYING(255),
	ROLE_ID BIGINT NOT NULL,
	FACEBOOK_KEY CHARACTER VARYING(255),
	FACEBOOK_UNIQUE_KEY CHARACTER VARYING(255),
    GOOGLE_UNIQUE_KEY CHARACTER VARYING(255),
	GOOGLE_KEY CHARACTER VARYING(255),
	APPLE_KEY CHARACTER VARYING(255),
	APPLE_UNIQUE_KEY CHARACTER VARYING(255),
	ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
	CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
	CREATED_BY NUMERIC(10,0) NOT NULL,
	UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,		
	UPDATED_BY NUMERIC(10,0) NOT NULL,	
	CONSTRAINT USER_LOGIN_PKEY PRIMARY KEY (ID),
	CONSTRAINT USER_LOGIN_ROLE FOREIGN KEY (ROLE_ID)
        REFERENCES ROLE (ID),
    CONSTRAINT USER_LOGIN_CONTACT_NUMBER_ENTITY_TYPE UNIQUE (ENTITY_TYPE, CONTACT_NUMBER),
	CONSTRAINT USER_LOGIN_EMAIL_ENTITY_TYPE UNIQUE (ENTITY_TYPE, EMAIL)
);

CREATE TABLE IF NOT EXISTS USER_OTP
(
    ID BIGSERIAL,
    USER_ID BIGINT NOT NULL,
    TYPE CHARACTER VARYING(20) NOT NULL,
    OTP_FOR CHARACTER VARYING(255) NOT NULL,
    OTP CHARACTER VARYING(6) NOT NULL,
    ACTIVE BOOLEAN NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    CREATED_BY BIGINT NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    UPDATED_BY BIGINT NOT NULL,
    CONSTRAINT USER_OTP_PKEY PRIMARY KEY (ID),
	CONSTRAINT USER_ID_TYPE_UNIQUE UNIQUE(USER_ID, TYPE),
    CONSTRAINT USER_ID_FK FOREIGN KEY (USER_ID)
        REFERENCES USER_LOGIN (ID)
);


